import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#1a365d',
        'primary-fixed': '#d6e3ff',
        'on-secondary': '#ffffff',
        'on-primary-container': '#86a0cd',
        'on-error-container': '#93000a',
        'on-background': '#1b1c1c',
        'tertiary-fixed-dim': '#c4c7ca',
        outline: '#74777f',
        'on-tertiary-container': '#9c9fa2',
        'primary-fixed-dim': '#adc7f7',
        'on-primary-fixed-variant': '#2d476f',
        'on-primary': '#ffffff',
        'on-surface-variant': '#43474e',
        'secondary-fixed-dim': '#96ccfb',
        'on-secondary-fixed-variant': '#004b72',
        'on-secondary-container': '#185982',
        tertiary: '#1d2124',
        'surface-container-high': '#eae8e7',
        'surface-container-highest': '#e4e2e1',
        'on-surface': '#1b1c1c',
        'on-tertiary-fixed': '#181c1f',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#44474a',
        'surface-container': '#f0eded',
        'inverse-on-surface': '#f3f0f0',
        'secondary-fixed': '#cce5ff',
        'surface-tint': '#455f88',
        'inverse-primary': '#adc7f7',
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed': '#001e31',
        'surface-variant': '#e4e2e1',
        primary: '#002045',
        'tertiary-fixed': '#e0e3e6',
        'surface-bright': '#fbf9f8',
        'error-container': '#ffdad6',
        'surface-dim': '#dcd9d9',
        'outline-variant': '#c4c6cf',
        surface: '#fbf9f8',
        secondary: '#27638d',
        'tertiary-container': '#333639',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#99cffe',
        background: '#fbf9f8',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#303030',
        'on-primary-fixed': '#001b3c',
        brand: {
          navy: '#1A365D',
          gold: '#C5A059',
          slate: '#64748B',
          surface: '#fbf9f8',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        card: '16px',
        button: '8px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '32px',
        gutter: '24px',
        'section-gap': '80px',
        margin: '32px',
        'stack-md': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['var(--font-noto-serif)', 'serif'],
        'headline-lg': ['var(--font-noto-serif)', 'serif'],
        'label-caps': ['var(--font-manrope)', 'sans-serif'],
        'body-lg': ['var(--font-manrope)', 'sans-serif'],
        'headline-xl': ['var(--font-noto-serif)', 'serif'],
        'body-md': ['var(--font-manrope)', 'sans-serif'],
        serif: ['var(--font-noto-serif)', 'serif'],
        sans: ['var(--font-manrope)', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
